### ISSUE TITLE
flask_oauthlib.client.OAuthException

### ISSUE THREAD

**Issue by alyzayn** [microsoftgraph/python-sample-pagination#4]
Traceback (most recent call last)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
Open an interactive python shell in this framereraise(exc_type, exc_value, tb)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\alizali\Desktop\Sample\sample.py", line 48, in authorized
response = MSGRAPH.authorized_response()
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask_oauthlib-0.9.4-py3.6.egg\flask_oauthlib\client.py", line 707, in authorized_response
data = self.handle_oauth2_response(args)
File "C:\Users\alizali\AppData\Local\Continuum\anaconda3\lib\site-packages\flask_oauthlib-0.9.4-py3.6.egg\flask_oauthlib\client.py", line 692, in handle_oauth2_response
type='invalid_response', data=data
flask_oauthlib.client.OAuthException: Invalid response from microsoft
Please help me with this

**Comment by alyzayn** [comment]
http://localhost:5000/login/authorized = MY REDIRECT URL

**Comment by Jackson-Woods** [comment]
This sample is being archived. Closing issue.
